scoring:
  weights:
    developing:
      wsjf: 0.5
      ice: 0.2
      technicalDebt: 0.2
      security: 0.1
    maturing:
      wsjf: 0.6
      ice: 0.1
      technicalDebt: 0.2
      security: 0.1
    advanced:
      wsjf: 0.5
      ice: 0.1
      technicalDebt: 0.3
      security: 0.1

  thresholds:
    minScore: 10
    maxRisk: 0.8
    securityBoost: 2.0
    complianceBoost: 1.8

discovery:
  sources:
    - gitHistory
    - staticAnalysis
    - issueTrackers
    - vulnerabilityDatabases
    - performanceMonitoring

  tools:
    staticAnalysis:
      - flake8
      - mypy
      - bandit
      - safety
    security:
      - bandit
      - safety
      - detect-secrets
    performance:
      - pytest-benchmark

execution:
  maxConcurrentTasks: 1
  testRequirements:
    minCoverage: 80
    performanceRegression: 5
  rollbackTriggers:
    - testFailure
    - buildFailure
    - securityViolation

repository:
  currentMaturity: "maturing"
  targetMaturity: "advanced"
  primaryLanguage: "python"
  framework: "pytorch-transformers"
  domain: "humanitarian-ai"