version: '3.8'

# Production overrides for docker-compose.yml
services:
  vislang-app:
    build:
      target: production
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - API_WORKERS=4
      - PROMETHEUS_METRICS_ENABLED=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  redis:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Remove jupyter service in production
  jupyter:
    profiles:
      - development

  # Enable monitoring by default in production
  prometheus:
    profiles:
      - default

  grafana:
    profiles:
      - default

secrets:
  postgres_password:
    external: true