name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please provide as much detail as possible to help us understand and reproduce the issue.
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Process document '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 13, Windows 11]
        - Python version: [e.g. 3.11.0]
        - VisLang version: [e.g. 1.0.0]
        - Installation method: [e.g. pip, conda, docker]
      value: |
        - OS: 
        - Python version: 
        - VisLang version: 
        - Installation method: 
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      description: Select the component where the bug occurs
      options:
        - Dataset processing
        - OCR engine
        - Model training
        - Data scraping
        - API endpoints
        - Documentation
        - Installation/Setup
        - Other (please specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Noticeable issue, affects functionality
        - High - Major issue, blocks important functionality
        - Critical - System unusable, data loss possible
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Screenshots, configuration files, etc.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true