name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🌟
        
        Please provide as much detail as possible to help us understand your request.
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear description of any alternative solutions or features you've considered.
      placeholder: Other options might be...
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      description: Select the component this feature would impact
      options:
        - Dataset processing
        - OCR engine
        - Model training
        - Data scraping
        - API endpoints
        - Documentation
        - Installation/Setup
        - Testing
        - CI/CD
        - Other (please specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for adoption
        - Critical - Blocking usage
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple change or addition
        - Medium - Moderate development effort
        - High - Significant development effort
        - Unknown - Not sure about implementation
    validations:
      required: false
      
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I work on humanitarian data analysis and need to...
        This feature would help me by...
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature X works as described
        - [ ] Documentation is updated
        - [ ] Tests are included
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
      
  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Have you done any research on this feature?
      options:
        - label: I have searched existing issues for similar requests
        - label: I have reviewed the documentation
        - label: I have considered alternative solutions
          
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true