# Automation Configuration for VisLang-UltraLow-Resource
# This file configures all automated tasks and workflows

automation:
  enabled: true
  log_level: INFO
  notification_channels:
    slack_webhook: ${SLACK_WEBHOOK_URL}
    email: ${NOTIFICATION_EMAIL}
    github_issues: true

# Metrics Collection Configuration
metrics_collection:
  enabled: true
  schedule: "0 0 * * *"  # Daily at midnight UTC
  config_file: ".github/project-metrics.json"
  collection_types:
    - repository
    - quality
    - security
    - infrastructure
    - build
  
  outputs:
    json: "metrics/daily-metrics.json"
    summary: "metrics/summary-report.md"
    dashboard_update: true
  
  thresholds:
    critical:
      test_coverage_below: 70.0
      critical_vulnerabilities_above: 0
      build_success_rate_below: 90.0
      uptime_below: 99.0
    
    warning:
      test_coverage_below: 80.0
      high_vulnerabilities_above: 5
      response_time_above_ms: 1000
      error_rate_above: 2.0

# Dependency Update Configuration
dependency_updates:
  enabled: true
  schedule: "0 6 * * 1"  # Weekly on Monday at 6 AM UTC
  
  auto_update:
    patch_updates: true
    security_updates: true
    minor_updates: false  # Require manual review
    major_updates: false  # Require manual review
  
  grouping:
    enabled: true
    groups:
      ml_core:
        - "torch*"
        - "transformers*"
        - "datasets*"
        - "accelerate*"
      
      ocr:
        - "*tesseract*"
        - "easyocr*"
        - "paddleocr*"
        - "opencv*"
      
      web:
        - "fastapi*"
        - "uvicorn*"
        - "pydantic*"
      
      testing:
        - "pytest*"
        - "coverage*"
        - "mock*"
      
      dev_tools:
        - "black*"
        - "isort*"
        - "flake8*"
        - "mypy*"
  
  security_advisory_check: true
  create_github_issues: true
  
  ignore:
    # Major version updates for core ML packages (manual review required)
    - package: "torch"
      update_types: ["major"]
    - package: "transformers"
      update_types: ["major"]
    - package: "datasets"
      update_types: ["major"]

# Release Automation Configuration
release_automation:
  enabled: true
  
  version_strategy: "semantic"  # semantic, calendar, build_number
  
  triggers:
    manual: true
    scheduled: false
    commit_patterns:
      - "feat:"
      - "fix:"
      - "feat!"
      - "fix!"
  
  pre_release_checks:
    run_tests: true
    check_coverage: true
    security_scan: true
    lint_check: true
    dependency_check: true
    
    thresholds:
      min_test_coverage: 80.0
      max_critical_vulnerabilities: 0
      max_high_vulnerabilities: 5
  
  changelog:
    generate: true
    format: "conventional"  # conventional, keep-a-changelog, custom
    categories:
      - name: "Features"
        patterns: ["feat:", "feature:"]
        emoji: "🚀"
      - name: "Bug Fixes"
        patterns: ["fix:", "bugfix:"]
        emoji: "🐛"
      - name: "Documentation"
        patterns: ["docs:", "doc:"]
        emoji: "📚"
      - name: "Performance"
        patterns: ["perf:", "performance:"]
        emoji: "⚡"
      - name: "Refactoring"
        patterns: ["refactor:", "refactoring:"]
        emoji: "♻️"
      - name: "Tests"
        patterns: ["test:", "tests:"]
        emoji: "🧪"
      - name: "Build System"
        patterns: ["build:", "deps:", "ci:"]
        emoji: "🔧"
  
  github_release:
    create: true
    draft: false
    prerelease_patterns:
      - "*-alpha*"
      - "*-beta*"
      - "*-rc*"
      - "*-dev*"
    
    assets:
      - "dist/*.whl"
      - "dist/*.tar.gz"
      - "sbom.spdx.json"
  
  notifications:
    slack: true
    email: true
    github_issue: false

# Code Quality Automation
code_quality:
  enabled: true
  
  pre_commit:
    enabled: true
    hooks:
      - black
      - isort
      - flake8
      - mypy
      - pytest-cov
      - safety
  
  continuous_monitoring:
    schedule: "0 2 * * *"  # Daily at 2 AM UTC
    
    checks:
      - name: "code_coverage"
        threshold: 80.0
        action: "warn"
      
      - name: "cyclomatic_complexity"
        threshold: 10
        action: "fail"
      
      - name: "maintainability_index"
        threshold: 70.0
        action: "warn"
      
      - name: "technical_debt_ratio"
        threshold: 5.0
        action: "warn"
  
  tools:
    sonarqube:
      enabled: false
      server_url: ${SONAR_HOST_URL}
      token: ${SONAR_TOKEN}
    
    codeclimate:
      enabled: false
      token: ${CODECLIMATE_REPO_TOKEN}
    
    codecov:
      enabled: true
      token: ${CODECOV_TOKEN}

# Security Automation
security:
  enabled: true
  
  vulnerability_scanning:
    schedule: "0 4 * * *"  # Daily at 4 AM UTC
    
    tools:
      - name: "safety"
        type: "python_dependencies"
        config: ".safety-policy.json"
      
      - name: "bandit"
        type: "code_analysis"
        config: ".bandit"
      
      - name: "trivy"
        type: "container_scanning"
        config: "trivy.yaml"
    
    severity_thresholds:
      critical: 0
      high: 0
      medium: 10
      low: -1  # No limit
  
  secret_scanning:
    enabled: true
    tools:
      - "truffleHog"
      - "detect-secrets"
    
    patterns:
      - "api_key"
      - "secret_key"
      - "password"
      - "token"
      - "private_key"
  
  compliance:
    enabled: true
    frameworks:
      - "OWASP"
      - "CIS"
      - "NIST"
    
    reports:
      schedule: "0 0 1 * *"  # Monthly on 1st at midnight
      format: ["json", "html", "pdf"]

# Infrastructure Monitoring
infrastructure:
  enabled: true
  
  health_checks:
    schedule: "*/5 * * * *"  # Every 5 minutes
    
    endpoints:
      - name: "api_health"
        url: "${API_URL}/health"
        timeout: 10
        expected_status: 200
      
      - name: "database"
        type: "database"
        connection_string: "${DATABASE_URL}"
        timeout: 5
  
  performance_monitoring:
    enabled: true
    
    metrics:
      - cpu_utilization
      - memory_usage
      - disk_usage
      - network_latency
      - response_time
      - error_rate
      - throughput
    
    alerting:
      cpu_threshold: 80.0
      memory_threshold: 85.0
      disk_threshold: 90.0
      error_rate_threshold: 5.0
      response_time_threshold: 2000  # ms
  
  backup:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM UTC
    
    targets:
      - database
      - configuration_files
      - user_data
    
    retention:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 3

# Notification Configuration
notifications:
  channels:
    slack:
      webhook_url: ${SLACK_WEBHOOK_URL}
      channel: "#vislang-alerts"
      mention_on_critical: "@channel"
    
    email:
      smtp_server: ${SMTP_SERVER}
      smtp_port: 587
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      from_email: "alerts@vislang.org"
      to_emails:
        - "dev-team@vislang.org"
        - "admin@vislang.org"
    
    github:
      create_issues: true
      labels:
        - "automated"
        - "alert"
      assignees:
        - "danieleschmidt"
    
    webhook:
      url: ${WEBHOOK_URL}
      headers:
        Authorization: "Bearer ${WEBHOOK_TOKEN}"
  
  escalation:
    levels:
      - name: "info"
        channels: ["slack"]
        delay_minutes: 0
      
      - name: "warning"
        channels: ["slack", "email"]
        delay_minutes: 15
      
      - name: "critical"
        channels: ["slack", "email", "github"]
        delay_minutes: 0
        repeat_interval_minutes: 60

# Reporting Configuration
reporting:
  enabled: true
  
  dashboards:
    grafana:
      url: "https://grafana.vislang.org"
      api_key: ${GRAFANA_API_KEY}
    
    custom:
      enabled: true
      output_dir: "reports"
      formats: ["html", "json", "csv"]
  
  schedules:
    daily_summary:
      enabled: true
      time: "08:00"
      timezone: "UTC"
      recipients: ["dev-team@vislang.org"]
    
    weekly_report:
      enabled: true
      day: "monday"
      time: "09:00"
      timezone: "UTC"
      recipients: ["management@vislang.org"]
    
    monthly_analysis:
      enabled: true
      day: 1
      time: "10:00"
      timezone: "UTC"
      recipients: ["stakeholders@vislang.org"]
  
  templates:
    daily_summary: "templates/daily-summary.html"
    weekly_report: "templates/weekly-report.html"
    monthly_analysis: "templates/monthly-analysis.html"

# Environment-Specific Configurations
environments:
  development:
    automation:
      enabled: true
      reduced_frequency: true
    notifications:
      channels: ["slack"]
      escalation: false
  
  staging:
    automation:
      enabled: true
      full_monitoring: true
    notifications:
      channels: ["slack", "email"]
      escalation: true
  
  production:
    automation:
      enabled: true
      full_monitoring: true
      strict_thresholds: true
    notifications:
      channels: ["slack", "email", "github"]
      escalation: true
      immediate_critical: true